# permissions for end users to view capsules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: capsules-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: observability-operator
    app.kubernetes.io/part-of: observability-operator
    app.kubernetes.io/managed-by: kustomize
  name: capsules-viewer-role
rules:
- apiGroups:
  - udmire.cn
  resources:
  - capsule
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - udmire.cn
  resources:
  - capsule/status
  verbs:
  - get
